### ISSUE TITLE
Helen: configuration files

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-kit#58]
At this moment helen configuration is spread in different places, and is not really usable. We need to put all the configs in a single place. We need to make sure `helen` runs robustly; thus, it is rather big task.

File: `helen-config.yaml`, overridden by default (embeded) empty configuration. Example:
```yaml
general:
  host: ip address
  port: 7654
  loglevel: warn
  logfile: filename.log (if not specified, send logs to std)
  service-restart-attempts: 10

trusted-clients:
  - 127.0.0.1
  - 129.132.32.138
  - ...

bundled-services:
  - siren:
      executable: siren.exe
      args: ...
  - another-service:
      executable: its-exe.exe
      args: cool-arg=4 ...
```

 * [ ] Default values for general section can be taken from current defaults
 * [ ] Merging configuration with default configuration should be preserved as it is now (and ideally with env variables too)
 * [ ] Ideally the whole checking should not ever fail only fallback to defaults with logged warnings
 * [ ] Should use monad logger to log errors/warnings
 * [ ] Need to implement and test: if one of the bundled services crashes, helen should try to restart it `service-restart-attempts` with all proper errors logged
 * [ ] Test whole configuration helen+siren+hs-example-service (either manually or set up test suite)
